// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlohaVietnam.Repositories.Models;

public partial class Clue
{
    public int Id { get; set; }

    public int PackageId { get; set; }

    public string Question { get; set; }

    public string AnswerCode { get; set; }

    public string Hint { get; set; }

    public int Points { get; set; }

    public int TimeBonus { get; set; }

    public int Order { get; set; }

    public virtual Package Package { get; set; }

    public virtual ICollection<UserProgress> UserProgresses { get; set; } = new List<UserProgress>();
}