// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlohaVietnam.Repositories.Models;

public partial class SideQuest
{
    public int Id { get; set; }

    public int PackageId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int Points { get; set; }

    public string Requirement { get; set; }

    public virtual Package Package { get; set; }

    public virtual ICollection<UserProgress> UserProgresses { get; set; } = new List<UserProgress>();
}