// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlohaVietnam.Repositories.Models;

public partial class SubscriptionPlan
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public int? DurationDays { get; set; }

    public int CityId { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}