// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlohaVietnam.Repositories.Models;

public partial class UserProgress
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public int PackageId { get; set; }

    public int? ClueId { get; set; }

    public int? SideQuestId { get; set; }

    public bool IsCompleted { get; set; }

    public int PointsEarned { get; set; }

    public DateTime? CompletionTime { get; set; }

    public virtual Clue Clue { get; set; }

    public virtual Package Package { get; set; }

    public virtual SideQuest SideQuest { get; set; }
}